### PR TITLE
added new feature - set custom background color

### PR DESCRIPTION
**Pull request by shalithasuranga**
Now background color of output image can be selected at the beginning. fixes 2 items of #27   checklist

### CODE REVIEW

**Comment by rehrumesh** [comment]
This is something you proposed new? Can you link the issue please? Otherwise before work on something new, better to discuss with the team. 

@chamathpali please check this.

**Comment by chamathpali** [comment]
@shalithasuranga this is a good feature to have. Keep white as default since this will be directly embedded in Readme's of repos. Also is there any impact on the file size with color and without color?

**Comment by shalithasuranga** [comment]
@rehrumesh This PR connects #27 . Okay Next time I will discuss before implement something. Thanks

**Comment by shalithasuranga** [comment]
@chamathpali 

Here is the comparison of files.

Output of current version 62KB

generated_overlap


PR version background "#ffff00" and opacity 1   75KB

new-op-1

PR version background "#ffff00" and opacity 0.5  73KB

new-op-0 5

PR version background "#ffff00" and opacity 0   71KB

new-op-0

Large files 

Current version : 3.3 MB
PR version background "#ffff00" and opacity  1 :  4.1 MB

it seems there is bit increase in size when colors added and opacity in mid value
We are not able to generate alpha levels in jpg. That's why I changed to .png
Your ideas please

Thanks

**Comment by rehrumesh** [comment]
@chamathpali Please review

**Review by chamathpali — APPROVED** [review]
Its good. lets proceed with it

**Comment by chamathpali** [comment]
Thanks @shalithasuranga  👍  Good work

**Pull request merged**
